[package]
name = "altio_test"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
altio = { path = "../altio" }
once_cell = { version = "1.19.0", optional = true }

[features]
default = ["altio", "reexport-stdio"]
altio = ["once_cell"]
reexport-stdio = []
